// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs8E9NE3kPedZ-0XKv0vceXSOQTQGOy88',
    appId: '1:559527690333:web:e300874554fbbaaa6d0db4',
    messagingSenderId: '559527690333',
    projectId: 'iot-akg',
    authDomain: 'iot-akg.firebaseapp.com',
    storageBucket: 'iot-akg.firebasestorage.app',
    measurementId: 'G-DYJMPKH56H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdWPCKDv1ttDk8SW9jA6asIWO2eAbdmY',
    appId: '1:559527690333:android:b674362141df7d366d0db4',
    messagingSenderId: '559527690333',
    projectId: 'iot-akg',
    storageBucket: 'iot-akg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivxdyRhxGueQaKCuU4Iunk4PG0sUTDps',
    appId: '1:559527690333:ios:c057c6ffe55a44c16d0db4',
    messagingSenderId: '559527690333',
    projectId: 'iot-akg',
    storageBucket: 'iot-akg.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivxdyRhxGueQaKCuU4Iunk4PG0sUTDps',
    appId: '1:559527690333:ios:c057c6ffe55a44c16d0db4',
    messagingSenderId: '559527690333',
    projectId: 'iot-akg',
    storageBucket: 'iot-akg.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs8E9NE3kPedZ-0XKv0vceXSOQTQGOy88',
    appId: '1:559527690333:web:d64c8ba5b24243fb6d0db4',
    messagingSenderId: '559527690333',
    projectId: 'iot-akg',
    authDomain: 'iot-akg.firebaseapp.com',
    storageBucket: 'iot-akg.firebasestorage.app',
    measurementId: 'G-FZVVKT654L',
  );
}
